[MOSIP-23969]
mosip/mosip-utilities pull request #38
Opened 2024-07-10 20:48 UTC by bhumi46

added docker file openssl creation for regclient

2024-07-11 11:42 UTC, syedsalman3753 approved these changes

2024-07-11 12:25 UTC, ckm007 requested changes

2024-07-11 12:25 UTC, ckm007 commented on openssl-regclient-1.1.1/client-openssl.cnf
> +[req]
get content approved by @Mahesh-Binayak

2024-07-11 12:25 UTC, ckm007 commented on openssl-regclient-1.1.1/client-openssl.cnf
regclient-openssl.cnf

2024-07-11 12:25 UTC, ckm007 commented on openssl-regclient-1.1.1/Dockerfile
> +    echo "${container_user} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
get it verified by @Mahesh-Binayak

2024-07-14 11:52 UTC, bhumi46 commented on openssl-regclient-1.1.1/README.md
> +This repository provides a Docker image and Kubernetes Job configuration for generating test certificates and secrets. It uses OpenSSL to create a Root CA certificate and a Client certificate, and th
updated over view

2025-01-24 10:14 UTC, closed without merging